@startuml Figure 4:Product Example
' Product example

skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 100

package "Product Definition Example" as PDF {

  package "Layer 1: Product Definition" as L1 {
    abstract class Product {
      +identifier
      +type
      +name : Text
      +description : Text
    }
  }

package "Layer 2: Product Business Schemas" as L2 {
  package "Boarding Product Schema" as BPS {
    object BoardingProduct <<Product>> {
      +schema_name = Priority Boarding @Gate
      +schema_description = Provides priority access to the 
      plane based on the zone bought.
      -----
      For features see next section; The attributes from the 'Product' 
      are not yet instntiated. That will be done on the concrete product 
      layer 
  }
  }

  Product <|-- BoardingProduct

  package "Transport Product Schema" as TPS {
    object TransportProduct <<Product>> {
      +schema_name: Transport
      +schema_description : Provides transport by means of either
      a plane, bus, train or boat from point A to point B
      without any intermediate stops except for technical stops. 
      -----
      For features see next section; The attributes from the 'Product' 
      are not yet instntiated. That will be done on the concrete product 
      layer
    }
  }

  Product <|-- TransportProduct
}
}


@enduml